# Generated by Django 5.0.7 on 2024-10-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
