# Generated by Django 4.2.20 on 2025-04-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('file_id', models.CharField(max_length=255)),
                ('intake_status', models.BooleanField(default=True)),
            ],
        ),
    ]
