# Generated by Django 4.2.20 on 2025-07-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationseason',
            old_name='event_name',
            new_name='season_name',
        ),
    ]
