# Generated by Django 5.0.7 on 2024-10-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('file_id', models.CharField(max_length=255)),
                ('intake_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.DeleteModel(
            name='VolunteerIntakeStatus',
        ),
    ]
