# Generated by Django 5.0.7 on 2024-10-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=555),
        ),
    ]
