# Generated by Django 5.0.7 on 2024-10-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_pic_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
