# Generated by Django 5.0.7 on 2024-10-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_profile_pic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profile_pic_url',
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.URLField(blank=True),
        ),
    ]
