# Generated by Django 5.0.7 on 2024-10-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_profile_pic_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
