# Generated by Django 5.1.1 on 2024-12-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_member_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membertoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AddField(
            model_name='member',
            name='member_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='MemberToken',
        ),
    ]
